Added some scripts, modified some others, changed and added some configs

diff --git a/.local/bin/compile b/.local/bin/compile
--- a/.local/bin/compile
+++ b/.local/bin/compile
@@ -7,18 +7,41 @@ ext="${file##*.}"
 
 tex_cleanup () {
 	rm "$basename.aux" >/dev/null 2>&1
-	rm "$basename.toc" >/dev/null 2>&1
+	#rm "$basename.toc" >/dev/null 2>&1 # The table of contents
 	rm "$basename.nav" >/dev/null 2>&1
 	rm "$basename.out" >/dev/null 2>&1
 	rm "$basename.snm" >/dev/null 2>&1
 
-    [ "$1" = "--keep-log" ] || rm "$basename.log" >/dev/null 2>&1
+    # Bibliography-related
+	#rm "$basename.bcf" >/dev/null 2>&1
+	#rm "$basename.bbl" >/dev/null 2>&1
+	rm "$basename.run.xml" >/dev/null 2>&1
+
+    if [ "$1" = "--keep-log" ]
+    then
+        a=1
+    else
+        rm "$basename.blg" >/dev/null 2>&1
+        rm "$basename.log" >/dev/null 2>&1
+    fi
 }
 
 # Compile a latex file
 tex_compile () {
-    { xelatex --output-directory="$dir" "$file" >/dev/null 2>&1 && tex_cleanup ;} || { echo "ERROR: Could not compile. Check the log." && tex_cleanup --keep-log ;}
-    #{ xelatex --output-directory="$dir" "$file" >/dev/null 2>&1 && tex_cleanup ;} || { echo "ERROR: Could not compile. Check the log." && tex_cleanup --keep-log && sleep 3 ;}
+    #{ xelatex --output-directory="$dir" "$file" >/dev/null 2>&1 && tex_cleanup ;} || { echo "ERROR: Could not compile. Check the log." && tex_cleanup --keep-log ;}
+    xelatex --output-directory="$dir" "$file" >/dev/null 2>&1 || { echo "ERROR: Could not compile. Check the log." && tex_cleanup --keep-log ;}
+
+    #if [ -f "$basename.bcf" ]
+    #then
+    #    if biber "$basename" >/dev/null 2>&1
+    #    then
+    #        xelatex --output-directory="$dir" "$file" >/dev/null 2>&1 || { echo "ERROR: Could not compile. Check the log." && tex_cleanup --keep-log  && exit ;}
+    #    else
+    #        echo "ERROR: Could not compile bibliography. Check the log." && tex_cleanup --keep-log && exit
+    #    fi
+    #fi
+
+    tex_cleanup
 }
 
 # Compile a groff file
